name : daigofuji's github page
brand : daigofuji.github.io
description : Daigo Fujiwara's github homepage - Front-end developer, UX, DataViz
keyword: Daigo Fujiwara, front end developer, github, Boston 
url : http://daigofuji.github.io/
email : daigo@daigofujiwara.com
author: Daigo Fujiwara
